
yarsha_agency_profile_show:
    path: /
    defaults: { _controller: "FOSUserBundle:Profile:show" }
    methods: "GET"

yarsha_agency_profile_edit:
    path: /edit
    defaults: { _controller: "FOSUserBundle:Profile:edit" }
