
yarsha_job_seeker_group_list:
    path: /list
    defaults: { _controller: "FOSUserBundle:Group:list" }
    methods: "GET"

yarsha_job_seeker_group_new:
    path: /new
    defaults: { _controller: "FOSUserBundle:Group:new" }

yarsha_job_seeker_group_show:
    path: /{groupName}
    defaults: { _controller: "FOSUserBundle:Group:show" }
    methods: "GET"

yarsha_job_seeker_group_edit:
    path: /{groupName}/edit
    defaults: { _controller: "FOSUserBundle:Group:edit" }

yarsha_job_seeker_group_delete:
    path: /{groupName}/delete
    defaults: { _controller: "FOSUserBundle:Group:delete" }
    methods: "GET"
