<?php
namespace Yarsha\OrganizationBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Yarsha\OrganizationBundle\Entity\OrganizationBannerImages;

/**
 * OrganizationBannerImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationBannerImagesRepository extends EntityRepository
{

    public function getBanners($id, $limit)
    {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('b')
            ->from(OrganizationBannerImages::class, 'b')
            ->where('b.status = :status')->setParameter('status', 1)
            ->andWhere('b.employer = :empID')->setParameter('empID', $id)
            ->orderBy('b.order', 'ASC');

        $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }


    public function findFeaturedBanner($id, $empID)
    {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('b')
            ->from(OrganizationBannerImages::class, 'b')
            ->where('b.status = :status')->setParameter('status', 1)
            ->andWhere('b.employer = :empID')->setParameter('empID', $empID)
            ->andWhere('b.id != :ID')->setParameter('ID', $id);


        return $qb->getQuery()->getResult();
    }


    public function getBannersToDelete($org)
    {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('b')
            ->from(OrganizationBannerImages::class, 'b')
            ->andWhere('b.employer = :empID')->setParameter('empID', $org);

        return $qb->getQuery()->getResult();
    }


}
