<?php

namespace Yarsha\OrganizationBundle\Repository;

/**
 * OrganizationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
