<?php

namespace Yarsha\OrganizationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrganizationSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationSettingRepository extends EntityRepository
{
}
