<?php

namespace Yarsha\OrganizationBundle\Repository;

/**
 * OrganizationContactPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationContactPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
