<?php

namespace Yarsha\OrganizationBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * OrganizationOwnershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationAutoEmailResponderRepository extends EntityRepository
{

}
