<?php

namespace Yarsha\OrganizationBundle\Repository;

/**
 * OrganizationSizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationSizeRepository extends \Doctrine\ORM\EntityRepository
{
}
