<?php

namespace Yarsha\JobSeekerBundle\Repository;

/**
 * EmployeeJobBasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeJobBasketRepository extends \Doctrine\ORM\EntityRepository
{
}
