<?php

namespace Yarsha\JobSeekerBundle\Repository;

/**
 * JobSeekerTrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSeekerTrainingRepository extends \Doctrine\ORM\EntityRepository
{
}
