<?php

namespace Yarsha\JobSeekerBundle\Repository;

/**
 * JobSeekerSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSeekerSettingRepository extends \Doctrine\ORM\EntityRepository
{
}
