<?php

namespace Yarsha\JobSeekerBundle\Repository;

/**
 * CoverLetterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSeekerCallRecordRepository extends \Doctrine\ORM\EntityRepository
{
}
