<?php

namespace Yarsha\JobSeekerBundle\Repository;

/**
 * JobSeekerExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSeekerExperienceRepository extends \Doctrine\ORM\EntityRepository
{
}
