<?php

namespace Yarsha\JobSeekerBundle\Repository;

/**
 * JobSeekerLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSeekerLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
