<?php

namespace Yarsha\JobSeekerBundle\Repository;

/**
 * JobSeekerReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSeekerReferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
