<?php

namespace Yarsha\JobSeekerBundle\Repository;

/**
 * JobSeekerEducationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSeekerEducationRepository extends \Doctrine\ORM\EntityRepository
{
}
