<?php

namespace Yarsha\JobSeekerBundle\Repository;

/**
 * ProfileCompletionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileCompletionRepository extends \Doctrine\ORM\EntityRepository
{
}
