# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider


    sonata.block.service.rss:
            class: Sonata\BlockBundle\Block\Service\RssBlockService
            arguments:
                - sonata.block.service.rss
                - "@templating"
            tags:
                - { name: sonata.block }
    yarsha.frontend.service.job:
            class: Yarsha\FrontendBundle\Service\JobBlockService
            arguments:
                - yarsha.frontend.service.job
                - "@templating"
            tags:
                - { name: sonata.block }
            #        Injecting entity manager through setter
            calls:
                        - [setEntityManager, ['@doctrine.orm.entity_manager']]

            #            Injecting entity manager as property
            #        properties:
            #            em: '@doctrine.orm.entity_manager'


    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener

        tags:

        - { name: doctrine.event_subscriber, connection: default }

        calls:

        - [ setAnnotationReader, [ "@annotation_reader" ] ]
