<?php

namespace Yarsha\JobsBundle\Repository;

/**
 * JobAppliedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobAppliedRepository extends \Doctrine\ORM\EntityRepository
{
}
