<?php

namespace Yarsha\JobsBundle\Repository;


use Doctrine\ORM\EntityRepository;
use Yarsha\JobsBundle\Entity\JobLevel;

/**
 * JobLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobLevelRepository extends EntityRepository
{

    public function getAllJobLevels(){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('j')
            ->from(JobLevel::class, 'j')
            ->where('j.deleted = 0')
            ->orderBy('j.sortOrder')
        ;
        return $qb->getQuery()->getResult();
    }
}
