<?php

namespace Yarsha\JobsBundle\Repository;

/**
 * JobSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSettingRepository extends \Doctrine\ORM\EntityRepository
{

    
}
