<?php

namespace Yarsha\ArticleBundle\Repository;

/**
 * ArticleTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleTagRepository extends \Doctrine\ORM\EntityRepository
{
}
