<?php

namespace Yarsha\TagsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Yarsha\TagsBundle\Entity\TagDescription;

/**
 * TagDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagDescriptionRepository extends EntityRepository
{

    public function listTagDescriptionsByTagQuery($slug)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('td')->from(TagDescription::class, 'td')
            ->leftJoin('td.tag', 't')
            ->where('t.slug = :slug')->setParameter('slug', $slug);

        return $qb;
    }
}
